trigger:
  branches:
    include:
      - main

stages:
  - stage: windows_2022
    displayName: 'windows-2022'
    dependsOn: [ ]
    pool:
      vmImage: 'windows-2022'
    jobs:
      - job: CreatePackage
        displayName: 'CreatePackage'
        dependsOn: [ ]
        steps:
          - task: CmdLine@2
            inputs:
#if (Bundle && Installer)
              script: './.nuke/build.cmd CreateBundle CreateInstaller'
#elseif (Installer)
              script: './.nuke/build.cmd CreateInstaller'
#elseif (Bundle)
              script: './.nuke/build.cmd CreateBundle'
#else
              script: './.nuke/build.cmd'
#endif
          - task: PublishBuildArtifacts@1
            inputs:
              artifactName: Nice3point.Revit.AddIn
              pathtoPublish: 'output'